### ISSUE TITLE
Import Documentation

### ISSUE THREAD

**Issue by AxelHo** [e-Spirit/FSDevTools#2]
Hi, 
thanks for this useful plugin.
I was able to export my project without problems.
After editing **one** file i was using the import statement without any flags.
The console gave me this info of updating 81 files:
**INFO - updated elements: 81**
Is it possible to only update the one edited file. and soime kind of watcher?
Otherwise the turnaround times for template editing are to long...

**Comment by AxelHo** [comment]
So if i only want to edit Section Templates, can i remove everthing from the export except the Sections?
Maybe it is getting a bit faster than?
I stopped a full import of an templatestore export after half an hour

**Comment by zaplatynski-espirit** [comment]
Hi Axel, that is the idea behind the reason why we dropped the `fs-cli export all` command in version 2.x. If you have bigger projects an export could take very long. So instead of export all at once you would export smaller chunks which is possible since you could export each substore like `fs-cli export  path:/templatestore/pagetemplates`. See `fs-cli help export` for more information and examples. I hope that helps. 

If you need to discuss the usage of the FS CLI please visit to our community at https://community.e-spirit.com (it is moderated and you get faster feedback). Bugs and feature requests are welcome here. Thanks!
