### ISSUE TITLE
Clarify Import/Export

### ISSUE THREAD

**Issue by ykorzikowski** [e-Spirit/FSDevTools#57]
Hi, 

as I stated out in my other issue I am currently automating the provisioning of FirstSpirit. 

It is a bit unclear to me, how the import/export on the gui and the fs-cli tool is working and if they are doing the same. 

As far as I understand, there are two options of export: Full Project Export (`fs-cli project export` and only the First Spirit content `fs-cli export`). 

The first one on the GUI gives me a big tar.gz, the second a slim zip file. 

However, how can I import the tar.gz file with the fs-cli? This is my approach so far: 

```
#!/bin/bash

# WARNING: This file is managed by Ansible.
# DO NOT EDIT THIS FILE MANUALLY.
# Any changes made directly to this file may be overwritten by Ansible.

set -eux

export JAVA_HOME="/usr/java/latest/"

sh {{ fs_cli_path }} \
-e \
-port "{{ fs_tomcat_port }}" \
-p "{{ fs_project_name }}" \
-h "{{ fs_host_name }}" \
-u admin \
-pwd "{{ fs_admin_password }}" \
-sd "{{ fs_content_dir }}" \
import
```

I choose the tar.gz for fs_content_dir , but it expects a unpacked directory. Do I need to unpack this tar.gz first or is there also a option to add the tar.gz as parameter?

Thanks in advance :)

**Comment by kafmann-e-spirit** [comment]
Hey @ykorzikowski,

I'm not quite sure if I understand you correctly but I will try to help :)

First of all, the CLI does have different commands for different export scenarios:

- fs-cli project export/import : these ones can be used to perform a complete project export/import as a *.tar.gz just like doing a project export/import in the ServerManager ( [Documentation on docs.e-spirit.com](https://docs.e-spirit.com/odfs/edocs/admi/firstspirit-ser/menu-bar-items/project/index.html) )
- fs-cli export/import : these ones perform an export/import of the given elements by using ExternalSync as the export format. This is typically used for GIT-Based enviroments because you have readable textfiles (_Sidenote_: external editing is not supposed to be done, unless you know exactly what to do). This enables you to perform branch based development in projects by using GIT as the data-repository. ( [Usecase description and additional documentation](https://docs.e-spirit.com/odfs/edocs/sync/index.html) )
- fs-cli feature ... : those commands can be used to create ContentTransport feature files (zip-files) that can be used for other transport scenarios where the other commands don't fit or if you just have another usecase that typically uses ContentTransport. ( [Documentation for ContentTransport - see chapter 4](https://docs.e-spirit.com/odfs/documentation/modules/developers/CONT_EN_FirstSpirit_CorporateContent.pdf) )

I hope this clarifies it a bit, but feel free to ask more :)

**Comment by ykorzikowski** [comment]
Hi @kafmann-e-spirit , 

yes this helped a lot. Checking the source for the correct cli parameters helped, too :) https://github.com/e-Spirit/FSDevTools/blob/82c7455e751c86dd95850a60ce8463aa80eac313/fsdevtools-commands/project/src/main/java/com/espirit/moddev/cli/commands/project/exportCommand/ExportProjectCommand.java#L51
