### ISSUE TITLE
Return Codes not valid - How to use in Jenkins?

### ISSUE THREAD

**Issue by Florian-Lenz** [e-Spirit/FSDevTools#6]
The fs-cli tool writes an error code to standard out (e.g. "Major error (code 202): An authentication failure with FirstSpirit occurred"), but the return-code of the command is always 0.

How to use this tool in a Jenkins Pipeline?

**Comment by mikula-espirit** [comment]
This should not happen, what command were you executing?

**Comment by Florian-Lenz** [comment]
Does happen with every error using Version 1.0.354 which is the only version, which is compatible with First Spirit 5.2.312.
On newer versions you will get a return-code.
In Version 1.0.498 an incorrect password will result in an error-message "Major error (code 202): An authentication failure with FirstSpirit occurred" but still responds with an RC=0.
Only Version 2.0.574 also handles this error correct.
Unfortunately all versions > 1.0.354 will not work with FS 5.2.312.

**Comment by mikula-espirit** [comment]
How about updating your FirstSpirit then?
In addition, you could try to use the latest version with your older access.jar. This may work for your case.

**Comment by Florian-Lenz** [comment]
Updating FirstSpirit is not an option now. Too expensive checking, testing and updating of all projects. I used all versions with the fs-access.jar of FS 5.2.312 as written in the documentation. Without any success.

**Comment by mikula-espirit** [comment]
Ok, this could be because there was/is a change in the behaviour of FS (a new exception gets thrown etc.). Let me ask this again: What command did you execute?

**Comment by Florian-Lenz** [comment]
/srv/fs-cli/bin/fs-cli -p <projectname> -port 8080 -u $FS_USER -pwd $FS_PASS -h <hostname> -sd $WORKSPACE/templates import

**Comment by mikula-espirit** [comment]
Ok, I've investigated some time in this issue and you are right, the exit code is broken but, it this has already been fixed for the latest version. 

Here is what you could do:

1. You could fork this and build your own custom version of the fs-cli using your fs-access.jar, you may need to uncomment //edit some lines of code to make it work, but the code for your version is available here, so this should not be too hard.
2. Update your system. You are currently using FS 5.2.312, afaik this is not a stable release anyway. I would prefer to use a stable marked release in a production environment. 
Our core team has changed a lot, to make distributed development working, so even your development process should benefit from an update.

**Comment by Florian-Lenz** [comment]
Hello Mikula,
I assume, you are an employee of e-Spirit. So please contact Daniel Witt.

1. Do you want your customers, to do your work? Before I do this, I will build my complete own tool based on the API.
2. Daniel can tell you, how expensive a migration to another (instable) version for our customer is. (Btw: When can we expect the first stable version at all?)

**Comment by mikula-espirit** [comment]
Hello Mr. Lenz,
you are right, I am an employee of e-Spirit and I was on vacation for the last weeks, so I'm sorry for the late response. 

This project is free software. Free means that we are giving away our knowledge and experience for free. We do not expect our customers to do 'our work'. Instead our customers can participate in this project and make suggestions (or simply make pull requests) to add even more functionality. If you want to implement your own tool, get inspired by this project or even use whole parts of the given source code, as this is the idea of free software. 
I am sorry if you did run into trouble with older implementations or their corresponding builds. Please be asured, if we do notice a bug in our software, we fix it as soon as possible. In this case, the bug you mention has already been fixed. What you want us to do is a merge of this bugfix into an older version. I can understand this request, but we won't fullfill this request, at least not for free. To make you understand why we won't do this, let's compare a piece of software with a book. This is easily done, because both are written word. In the current case, we have already delivered the errata and the corrigenda. You want us to remove pages form your book and glue the corresponding corrigenda into your book. I do not know any book publishing company, who will do this. If you would ask them to, they will send you a newer release of the book instead. The process of page cutting and glueing takes a lot of time and provides additional expenses for a product that already is free.
I have contacted Daniel, as far as I have understood, further communication will be handled by him.

best regards 
Martin Mikula
